// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce_ui_clone/test/features/authentication/presentatioin/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ecommerce_ui_clone/core/error/failures.dart' as _i6;
import 'package:ecommerce_ui_clone/core/success/success.dart' as _i9;
import 'package:ecommerce_ui_clone/features/authentication/domain/entity/user.dart'
    as _i7;
import 'package:ecommerce_ui_clone/features/authentication/domain/repository/auth_repository.dart'
    as _i2;
import 'package:ecommerce_ui_clone/features/authentication/domain/usecase/log_in_usecase.dart'
    as _i4;
import 'package:ecommerce_ui_clone/features/authentication/domain/usecase/log_out_usecase.dart'
    as _i8;
import 'package:ecommerce_ui_clone/features/authentication/domain/usecase/sign_up_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogInUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogInUsecase extends _i1.Mock implements _i4.LogInUsecase {
  MockLogInUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.User>> call({
    required dynamic email,
    required dynamic password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.User>>.value(
              _FakeEither_1<_i6.Failure, _i7.User>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.User>>);
}

/// A class which mocks [LogOutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogOutUsecase extends _i1.Mock implements _i8.LogOutUsecase {
  MockLogOutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.Success>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i9.Success>>.value(
              _FakeEither_1<_i6.Failure, _i9.Success>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i9.Success>>);
}

/// A class which mocks [SignUpUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUsecase extends _i1.Mock implements _i10.SignUpUsecase {
  MockSignUpUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.Success>> call(
    dynamic name,
    dynamic email,
    dynamic password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [name, email, password]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i9.Success>>.value(
              _FakeEither_1<_i6.Failure, _i9.Success>(
                this,
                Invocation.method(#call, [name, email, password]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i9.Success>>);
}
