// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce_ui_clone/test/features/chat/data/repositories/chat_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ecommerce_ui_clone/features/authentication/data/model/user_model.dart'
    as _i6;
import 'package:ecommerce_ui_clone/features/chat/data/datasources/chat_remote_data_source.dart'
    as _i4;
import 'package:ecommerce_ui_clone/features/chat/data/datasources/chat_socket_data_source.dart'
    as _i8;
import 'package:ecommerce_ui_clone/features/chat/data/models/chat_model.dart'
    as _i2;
import 'package:ecommerce_ui_clone/features/chat/data/models/message_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatModel_0 extends _i1.SmartFake implements _i2.ChatModel {
  _FakeChatModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageModel_1 extends _i1.SmartFake implements _i3.MessageModel {
  _FakeMessageModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteDataSource extends _i1.Mock
    implements _i4.ChatRemoteDataSource {
  MockChatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.UserModel>> getAllUsers({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, [], {#token: token}),
            returnValue: _i5.Future<List<_i6.UserModel>>.value(
              <_i6.UserModel>[],
            ),
          )
          as _i5.Future<List<_i6.UserModel>>);

  @override
  _i5.Future<List<_i2.ChatModel>> getUserChats({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChats, [], {#token: token}),
            returnValue: _i5.Future<List<_i2.ChatModel>>.value(
              <_i2.ChatModel>[],
            ),
          )
          as _i5.Future<List<_i2.ChatModel>>);

  @override
  _i5.Future<List<_i3.MessageModel>> getChatMessages({
    required String? chatId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [], {
              #chatId: chatId,
              #token: token,
            }),
            returnValue: _i5.Future<List<_i3.MessageModel>>.value(
              <_i3.MessageModel>[],
            ),
          )
          as _i5.Future<List<_i3.MessageModel>>);

  @override
  _i5.Future<_i2.ChatModel> initiateChat({
    required String? userId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateChat, [], {
              #userId: userId,
              #token: token,
            }),
            returnValue: _i5.Future<_i2.ChatModel>.value(
              _FakeChatModel_0(
                this,
                Invocation.method(#initiateChat, [], {
                  #userId: userId,
                  #token: token,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ChatModel>);

  @override
  _i5.Future<void> deleteChat({
    required String? chatId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [], {
              #chatId: chatId,
              #token: token,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.MessageModel> sendMessage({
    required String? chatId,
    required String? content,
    required String? type,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatId: chatId,
              #content: content,
              #type: type,
              #token: token,
            }),
            returnValue: _i5.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#sendMessage, [], {
                  #chatId: chatId,
                  #content: content,
                  #type: type,
                  #token: token,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.MessageModel>);

  @override
  _i5.Future<String> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getToken, [])),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [ChatSocketDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSocketDataSource extends _i1.Mock
    implements _i8.ChatSocketDataSource {
  MockChatSocketDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void connect() => super.noSuchMethod(
    Invocation.method(#connect, []),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage({
    required String? chatId,
    required String? content,
    required String? type,
  }) => super.noSuchMethod(
    Invocation.method(#sendMessage, [], {
      #chatId: chatId,
      #content: content,
      #type: type,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void onMessageDelivered(dynamic Function(_i3.MessageModel)? callback) =>
      super.noSuchMethod(
        Invocation.method(#onMessageDelivered, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void onMessageReceived(dynamic Function(_i3.MessageModel)? callback) =>
      super.noSuchMethod(
        Invocation.method(#onMessageReceived, [callback]),
        returnValueForMissingStub: null,
      );
}
